baseURL: https://example.com
languageCode: en-us
title: Elementary Example
theme: hugo-elementary
disableKinds:
  - term
params:
  disclaimer: foo
menu:
  main:
    - name: test
      url: https://example.com
